name: CI

on:
  pull_request:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check types
        run: mypy quex_backend --exclude 'td_quote\.py$' --exclude 'parsetab\.py$'

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV
      - name: Set environment variables
        run: |
          echo "CONFIG=$(pwd)/config.toml" >> $GITHUB_ENV
          echo "ETH_SIGNER_KEY_FILE=sk.txt" >> $GITHUB_ENV
          echo "DEBUG=1" >> $GITHUB_ENV
      - name: Run tests
        run: pytest
